// <auto-generated />
namespace Roz.Identity.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SecurityInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecurityInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201504141439460_SecurityInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
