// <auto-generated />
namespace Roz.WebApp.Migrations.Books
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ConcurrencyHandling : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConcurrencyHandling));
        
        string IMigrationMetadata.Id
        {
            get { return "201502061502388_ConcurrencyHandling"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
