// <auto-generated />
namespace Roz.Data.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FirstDomainModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstDomainModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201504112105509_FirstDomainModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
